[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ideas"
dynamic = ["version"]
description = 'Easy creation of import hooks to test ideas.'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "André Roberge", email = "andre.roberge@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["token-utils"]

[project.urls]
Documentation = "https://aroberge.github.io/ideas/docs/html/"
Issues = "https://github.com/aroberge/ideas/issues"
Source = "https://github.com/aroberge/ideas"

[tool.hatch.version]
path = "src/ideas/__about__.py"

[project.scripts]
ideas = "ideas.__main__:main"
