@startuml
partition Finder #LightSkyBlue  {
    :Search for file;
    :Return file spec & Loader;
    }
partition Loader #LightSkyBlue  {
    :Create a module object;
    :Decode file;
    :Execute code in module dict;
    }
@enduml
